//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RC2K.Resources.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RC2K.Resources.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renault Mégane,A7
        ///Vauxhall Astra,A7
        ///Seat Cordoba WRC,A8
        ///Hyundai Coupé Evo II,A7
        ///Subaru Impreza WRC,A8
        ///Peugeot 106 Maxi, A6
        ///MF Turbo,A8
        ///Mitsubishi Lancer Evo V,A8
        ///Volkswagen Golf GTI MKIV,A7
        ///Nissan Almera,A7
        ///Proton Wira/Persona,A8
        ///Citroën Saxo,A6
        ///Honda Civic,A6
        ///Nissan Micra Maxi,A5
        ///Peugeot 206 WRC,A8
        ///Ford Escort RS2000,A7
        ///Škoda Octavia,A7
        ///Seat Ibiza Cupra Sport,A7
        ///Škoda Felicia,A6
        ///Proton Compact,A6
        ///Ford Escort RS2000,A7
        ///Ford Puma,A5,
        ///Mitsubishi Lancer Evo IV,A8.
        /// </summary>
        internal static string Cars {
            get {
                return ResourceManager.GetString("Cars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 21,Port Soderick
        ///22,Ballagyr
        ///23,Curraghs
        ///24,Tholt-y-Will
        ///25,Injerbreck
        ///26,Cringle
        ///31,Twiglees
        ///32,Yair
        ///33,Cardrona
        ///34,Black loch
        ///35,Glentrool
        ///36,Ae
        ///41,Clocaenog Mid
        ///42,Penmachno South
        ///43,Myherin
        ///44,Hafren
        ///45,Dyfi
        ///46,Gartheiniog
        ///51,Hamilton&apos;s Folly
        ///52,Tyrones ditches
        ///53,Feeney
        ///54,Parkanaur
        ///55,Lisnamuck
        ///56,Tardree
        ///61,Chirdonhead
        ///62,Falstone
        ///63,Kershope
        ///64,Pundershaw
        ///65,Riccarton
        ///66,Newcastleton
        ///71,Moon and star
        ///72,Bothwell
        ///73,Whitchester
        ///74,Eccles
        ///75,Langton
        ///76,Fogo.
        /// </summary>
        internal static string Stages {
            get {
                return ResourceManager.GetString("Stages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 21,&quot;54.1412097,-4.4701409;54.1355627,-4.4864447;54.1277141,-4.5221752;54.1266989,-4.5372641;54.114791,-4.569775;54.120478,-4.57988&quot;
        ///22,&quot;54.2262301,-4.6734796;54.2282370,-4.6504770;54.2179001,-4.6418939;54.2319497,-4.6293626;54.242985,-4.618033;54.248401,-4.6355424;54.2596334,-4.6223245;54.2722654,-4.6018968;54.2678098,-4.5894544;54.2610085,-4.5824171&quot;
        ///23,54.29255562,-4.5794437;54.3026520,-4.579188578701743;54.3082203634176, -4.564388361708989;54.32658008948149, -4.551420821392586;54.321536770938, -4.54376 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string StagesWaypoints {
            get {
                return ResourceManager.GetString("StagesWaypoints", resourceCulture);
            }
        }

        internal static string StagesDetails {
            get {
                return ResourceManager.GetString("StagesDetails", resourceCulture);
            }
        }

    }
}
