// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RC2K.DataAccess.Database;

#nullable disable

namespace RC2K.DataAccess.Database.Migrations
{
    [DbContext(typeof(RallyDbContext))]
    [Migration("20251027131809_waypoints")]
    partial class waypoints
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("RC2K.DomainModel.Car", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Class")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Cars");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Class = 7,
                            Name = "Renault Mégane"
                        },
                        new
                        {
                            Id = 2,
                            Class = 7,
                            Name = "Vauxhall Astra"
                        },
                        new
                        {
                            Id = 3,
                            Class = 8,
                            Name = "Seat Cordoba WRC"
                        },
                        new
                        {
                            Id = 4,
                            Class = 7,
                            Name = "Hyundai Coupé Evo II"
                        },
                        new
                        {
                            Id = 5,
                            Class = 8,
                            Name = "Subaru Impreza WRC"
                        },
                        new
                        {
                            Id = 6,
                            Class = 6,
                            Name = "Peugeot 106 Maxi"
                        },
                        new
                        {
                            Id = 7,
                            Class = 8,
                            Name = "MF Turbo"
                        },
                        new
                        {
                            Id = 8,
                            Class = 8,
                            Name = "Mitsubishi Lancer Evo V"
                        },
                        new
                        {
                            Id = 9,
                            Class = 7,
                            Name = "Volkswagen Golf GTI MKIV"
                        },
                        new
                        {
                            Id = 10,
                            Class = 7,
                            Name = "Nissan Almera"
                        },
                        new
                        {
                            Id = 11,
                            Class = 8,
                            Name = "Proton Wira/Persona"
                        },
                        new
                        {
                            Id = 12,
                            Class = 6,
                            Name = "Citroën Saxo"
                        },
                        new
                        {
                            Id = 13,
                            Class = 6,
                            Name = "Honda Civic"
                        },
                        new
                        {
                            Id = 14,
                            Class = 5,
                            Name = "Nissan Micra Maxi"
                        },
                        new
                        {
                            Id = 15,
                            Class = 8,
                            Name = "Peugeot 206 WRC"
                        },
                        new
                        {
                            Id = 16,
                            Class = 7,
                            Name = "Ford Escort RS2000"
                        },
                        new
                        {
                            Id = 17,
                            Class = 7,
                            Name = "Škoda Octavia"
                        },
                        new
                        {
                            Id = 18,
                            Class = 7,
                            Name = "Seat Ibiza Cupra Sport"
                        },
                        new
                        {
                            Id = 19,
                            Class = 6,
                            Name = "Škoda Felicia"
                        },
                        new
                        {
                            Id = 20,
                            Class = 6,
                            Name = "Proton Compact"
                        },
                        new
                        {
                            Id = 21,
                            Class = 7,
                            Name = "Ford Escort RS2000"
                        },
                        new
                        {
                            Id = 22,
                            Class = 5,
                            Name = "Ford Puma"
                        },
                        new
                        {
                            Id = 23,
                            Class = 8,
                            Name = "Mitsubishi Lancer Evo IV"
                        });
                });

            modelBuilder.Entity("RC2K.DomainModel.Driver", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Key")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Known")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int?>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Drivers", (string)null);
                });

            modelBuilder.Entity("RC2K.DomainModel.Stage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Code")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsArcade")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Code");

                    b.ToTable("Stages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = 21,
                            IsArcade = true
                        },
                        new
                        {
                            Id = 2,
                            Code = 21,
                            IsArcade = false
                        },
                        new
                        {
                            Id = 3,
                            Code = 22,
                            IsArcade = true
                        },
                        new
                        {
                            Id = 4,
                            Code = 22,
                            IsArcade = false
                        },
                        new
                        {
                            Id = 5,
                            Code = 23,
                            IsArcade = true
                        },
                        new
                        {
                            Id = 6,
                            Code = 23,
                            IsArcade = false
                        },
                        new
                        {
                            Id = 7,
                            Code = 24,
                            IsArcade = true
                        },
                        new
                        {
                            Id = 8,
                            Code = 24,
                            IsArcade = false
                        },
                        new
                        {
                            Id = 9,
                            Code = 25,
                            IsArcade = true
                        },
                        new
                        {
                            Id = 10,
                            Code = 25,
                            IsArcade = false
                        },
                        new
                        {
                            Id = 11,
                            Code = 26,
                            IsArcade = true
                        },
                        new
                        {
                            Id = 12,
                            Code = 26,
                            IsArcade = false
                        },
                        new
                        {
                            Id = 13,
                            Code = 31,
                            IsArcade = true
                        },
                        new
                        {
                            Id = 14,
                            Code = 31,
                            IsArcade = false
                        },
                        new
                        {
                            Id = 15,
                            Code = 32,
                            IsArcade = true
                        },
                        new
                        {
                            Id = 16,
                            Code = 32,
                            IsArcade = false
                        },
                        new
                        {
                            Id = 17,
                            Code = 33,
                            IsArcade = true
                        },
                        new
                        {
                            Id = 18,
                            Code = 33,
                            IsArcade = false
                        },
                        new
                        {
                            Id = 19,
                            Code = 34,
                            IsArcade = true
                        },
                        new
                        {
                            Id = 20,
                            Code = 34,
                            IsArcade = false
                        },
                        new
                        {
                            Id = 21,
                            Code = 35,
                            IsArcade = true
                        },
                        new
                        {
                            Id = 22,
                            Code = 35,
                            IsArcade = false
                        },
                        new
                        {
                            Id = 23,
                            Code = 36,
                            IsArcade = true
                        },
                        new
                        {
                            Id = 24,
                            Code = 36,
                            IsArcade = false
                        },
                        new
                        {
                            Id = 25,
                            Code = 41,
                            IsArcade = true
                        },
                        new
                        {
                            Id = 26,
                            Code = 41,
                            IsArcade = false
                        },
                        new
                        {
                            Id = 27,
                            Code = 42,
                            IsArcade = true
                        },
                        new
                        {
                            Id = 28,
                            Code = 42,
                            IsArcade = false
                        },
                        new
                        {
                            Id = 29,
                            Code = 43,
                            IsArcade = true
                        },
                        new
                        {
                            Id = 30,
                            Code = 43,
                            IsArcade = false
                        },
                        new
                        {
                            Id = 31,
                            Code = 44,
                            IsArcade = true
                        },
                        new
                        {
                            Id = 32,
                            Code = 44,
                            IsArcade = false
                        },
                        new
                        {
                            Id = 33,
                            Code = 45,
                            IsArcade = true
                        },
                        new
                        {
                            Id = 34,
                            Code = 45,
                            IsArcade = false
                        },
                        new
                        {
                            Id = 35,
                            Code = 46,
                            IsArcade = true
                        },
                        new
                        {
                            Id = 36,
                            Code = 46,
                            IsArcade = false
                        },
                        new
                        {
                            Id = 37,
                            Code = 51,
                            IsArcade = true
                        },
                        new
                        {
                            Id = 38,
                            Code = 51,
                            IsArcade = false
                        },
                        new
                        {
                            Id = 39,
                            Code = 52,
                            IsArcade = true
                        },
                        new
                        {
                            Id = 40,
                            Code = 52,
                            IsArcade = false
                        },
                        new
                        {
                            Id = 41,
                            Code = 53,
                            IsArcade = true
                        },
                        new
                        {
                            Id = 42,
                            Code = 53,
                            IsArcade = false
                        },
                        new
                        {
                            Id = 43,
                            Code = 54,
                            IsArcade = true
                        },
                        new
                        {
                            Id = 44,
                            Code = 54,
                            IsArcade = false
                        },
                        new
                        {
                            Id = 45,
                            Code = 55,
                            IsArcade = true
                        },
                        new
                        {
                            Id = 46,
                            Code = 55,
                            IsArcade = false
                        },
                        new
                        {
                            Id = 47,
                            Code = 56,
                            IsArcade = true
                        },
                        new
                        {
                            Id = 48,
                            Code = 56,
                            IsArcade = false
                        },
                        new
                        {
                            Id = 49,
                            Code = 61,
                            IsArcade = true
                        },
                        new
                        {
                            Id = 50,
                            Code = 61,
                            IsArcade = false
                        },
                        new
                        {
                            Id = 51,
                            Code = 62,
                            IsArcade = true
                        },
                        new
                        {
                            Id = 52,
                            Code = 62,
                            IsArcade = false
                        },
                        new
                        {
                            Id = 53,
                            Code = 63,
                            IsArcade = true
                        },
                        new
                        {
                            Id = 54,
                            Code = 63,
                            IsArcade = false
                        },
                        new
                        {
                            Id = 55,
                            Code = 64,
                            IsArcade = true
                        },
                        new
                        {
                            Id = 56,
                            Code = 64,
                            IsArcade = false
                        },
                        new
                        {
                            Id = 57,
                            Code = 65,
                            IsArcade = true
                        },
                        new
                        {
                            Id = 58,
                            Code = 65,
                            IsArcade = false
                        },
                        new
                        {
                            Id = 59,
                            Code = 66,
                            IsArcade = true
                        },
                        new
                        {
                            Id = 60,
                            Code = 66,
                            IsArcade = false
                        },
                        new
                        {
                            Id = 61,
                            Code = 71,
                            IsArcade = true
                        },
                        new
                        {
                            Id = 62,
                            Code = 71,
                            IsArcade = false
                        },
                        new
                        {
                            Id = 63,
                            Code = 72,
                            IsArcade = true
                        },
                        new
                        {
                            Id = 64,
                            Code = 72,
                            IsArcade = false
                        },
                        new
                        {
                            Id = 65,
                            Code = 73,
                            IsArcade = true
                        },
                        new
                        {
                            Id = 66,
                            Code = 73,
                            IsArcade = false
                        },
                        new
                        {
                            Id = 67,
                            Code = 74,
                            IsArcade = true
                        },
                        new
                        {
                            Id = 68,
                            Code = 74,
                            IsArcade = false
                        },
                        new
                        {
                            Id = 69,
                            Code = 75,
                            IsArcade = true
                        },
                        new
                        {
                            Id = 70,
                            Code = 75,
                            IsArcade = false
                        },
                        new
                        {
                            Id = 71,
                            Code = 76,
                            IsArcade = true
                        },
                        new
                        {
                            Id = 72,
                            Code = 76,
                            IsArcade = false
                        });
                });

            modelBuilder.Entity("RC2K.DomainModel.StageData", b =>
                {
                    b.Property<int>("StageCode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImgName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("StageCode");

                    b.ToTable("StagesData");

                    b.HasData(
                        new
                        {
                            StageCode = 21,
                            Description = "Finałowy etap Rajdu Walii jest stosunkowo kręty i pro wadzony w ciemności, ale doświadczeni kierowcy i tak mogą osiągać duże prędkości. Jest bardziej nierówny niż Dyfi, co zwiększa prawdopodobieństwo przebicia opony, ale szybsze odcinki są darem od Boga dla kierowców posiadających samochody o mniejszej mocy.",
                            ImgName = "MNX_001.PNG",
                            Name = "Port Soderick"
                        },
                        new
                        {
                            StageCode = 22,
                            Description = "Prawdziwie międzynarodowy etap Newcastleton rozpo czyna się w Szkocji, następnie przecina rzekę i wchodzi do Anglii. Sekcja początkowa jest ciasna, po czym kierowcy wchodzą na szybszy fragment drogi, która jest używana również w etapie Kershope. Następnie etap przechodzi na niziny z szybszymi i równiejszymi drogami.",
                            ImgName = "MNX_002.PNG",
                            Name = "Ballagyr"
                        },
                        new
                        {
                            StageCode = 23,
                            Description = "Najdłuższy etap w rajdzie. Ae był świadkiem kilku drama tycznych zakończeń i potrafi postawić na głowie tabelę wyników. Twarda nawierzchnia i otwarte zakręty spra wiają, że jest lubiany zarówno przez kierowców, jak i kibi ców, chociaż największe tłumy gromadzą się przy cias nych wirażach w lewo.",
                            ImgName = "MNX_003.PNG",
                            Name = "Curraghs"
                        },
                        new
                        {
                            StageCode = 24,
                            Description = "Końcowy etap posiada wszystkiego po trochu, a w tym ekstremalnie szybkie sekcje na gładkich drogach oraz serie wiraży wymagających cierpliwości i koncentracji. Również tu droga może być pokryta pozostałościami po pracach polowych, a w ciemności nocy trudno jest ocenić poziom przyczepności samochodu.",
                            ImgName = "MNX_004.PNG",
                            Name = "Tholt-y-Will"
                        },
                        new
                        {
                            StageCode = 25,
                            Description = "Większość etapów w rejonie płaskowyżu Antrim jest uznawana za zbyt szybkie dla współczesnych samocho dów rajdowych, ale Tardree jakoś udało się przeforsować. Jest to ciągle najszybszy sprawdzian rajdu. Super szybki finał jest klasycznym górskim etapem. Zawiera niewiele skrzyżowań i kilka bardzo szybkich prostych.",
                            ImgName = "MNX_005.PNG",
                            Name = "Injerbreck"
                        },
                        new
                        {
                            StageCode = 26,
                            Description = "Mistrzostwa Mobil 1 kończą się jednym z najtrudniejszych etapów. Ponad 20 km łączących w sobie szybkie, otwarte drogi kategorii B, wiejskie drogi i skomplikowane rozjazdy, a to wszystko jeszcze utrudnione ciemnością i ciężkim deszczem. Nie można wyobrazić sobie lepszego testu, który zdecyduje o tym, kto zgarnie wszystko.",
                            ImgName = "MNX_006.PNG",
                            Name = "Cringle"
                        },
                        new
                        {
                            StageCode = 31,
                            Description = "Będąc odzwierciedleniem klasycznego Rajdu Walii, Myth erin posiada kręty odcinek startowy wyprowadzający zawodników na sam grzbiet wzniesienia, aby po chwili rzucić ich na dno doliny. Środkowy odcinek rajdu jest szybki i pozwala na płynną jazdę, ale posiada mnóstwo wzniesień wymagających pełnego zaangażowania.",
                            ImgName = "SC_001.PNG",
                            Name = "Twiglees"
                        },
                        new
                        {
                            StageCode = 32,
                            Description = "Kilkukilometrowy początek Kershope zawiera jeden naj bardziej wymagających, leśnych odcinków rajdowych w Wielkiej Brytanii. Droga wydaje się być znacznie bardziej kręta niż jest naprawdę i odważniejsi kierowcy mogą w rezultacie znacznie nadrobić czas. Mgła w wyższych partiach wymaga od kierowców wzmożonej koncentracji.",
                            ImgName = "SC_002.PNG",
                            Name = "Yair"
                        },
                        new
                        {
                            StageCode = 33,
                            Description = "Niezwykle malowniczy etap Cardrona rozpoczyna się powolnym podjazdem pod wzniesienie, który kończy ostry zakręt w prawo. Środkowa część tego odcinka jest gęsto zalesiona, a droga jest szybsza i pozwala na bardziej płynną jazdę. Sekcja zjazdowa zwiększa prędkość i prowadzi zawodników w kierunku mety.",
                            ImgName = "SC_003.PNG",
                            Name = "Cardrona"
                        },
                        new
                        {
                            StageCode = 34,
                            Description = "Rozpoczynając się w pobliżu wioski Longformacus na wąs kiej wiejskiej drodze, etap ten wykorzystuje szeroką i szybką drogę kategorii B i kończy się na Abbey Road. Jest to również ostatni etap rajdu rozgrywany w świe tle dziennym, tak więc niedoświadczeni nocni kierowcy powinni atakować, kiedy tylko mogą.",
                            ImgName = "SC_004.PNG",
                            Name = "Black Loch"
                        },
                        new
                        {
                            StageCode = 35,
                            Description = "Trzeci sprawdzian jest jednym z najbardziej męczących dla kierowców, gdyż nie posiada zbyt wielu prostych dających im odpocząć po serii wiraży i zakrętów. Mimo, że oparty jest na stosunkowo gładkiej nawierzchni, etap ten zawiera wiele rozjazdów i zwodniczych łuków, które mogą zmylić nieuważnych. Kończy się na Feeney Road.",
                            ImgName = "SC_005.PNG",
                            Name = "Glentrool"
                        },
                        new
                        {
                            StageCode = 36,
                            Description = "Jako jeden z klasycznych etapów na wyspie Man, Cur raghs jest niezwykle wyboisty, bardzo wąski i niesamo wicie szybki. Ma kręte odcinki, ale średnie prędkości wciąż są wysokie. Uważaj na jego najsławniejszą cechę: doły i skoki w pobliżu mety, gdzie sprawdzian przecina główną drogę Jurby.",
                            ImgName = "SC_006.PNG",
                            Name = "Ae"
                        },
                        new
                        {
                            StageCode = 41,
                            Description = "Jest jednym z najtrudniejszych odcinków w lasach Walii. Obfituje we wzniesienia, a jego drogi są znacznie węższe od normalnych. Skrzyżowanie w Clocaenog potrafi być błotniste, a ostatnie zalecenia Komisji Leśnictwa znacznie utrudniły odczytywanie drogi.",
                            ImgName = "VRW_001.PNG",
                            Name = "Clocaenog Mid"
                        },
                        new
                        {
                            StageCode = 42,
                            Description = "To bardzo szybkie wprowadzenie do leśnego kompleksu Kieldera posiada wszystkie cechy tego legendarnego i rzucającego wyzwanie miejsca. Jest tu wiele długich, szybkich prostych ze ślepymi wzniesieniami i wąski most sprzyjający najodważniejszym kierowcom. Głębokie rowy są zdolne pochłonąć wypadający z drogi samochód.",
                            ImgName = "VRW_002.PNG",
                            Name = "Penmachno South"
                        },
                        new
                        {
                            StageCode = 43,
                            Description = "Rezerwat Black Esk jest miejscem otwierającym etap, który rozpoczyna się od jazdy wzdłuż rzeki Esk w sza rówce wczesnego poranka. Następnie występuje gęsto zadrzewiona sekcja posiadająca wiele szybkich prostych i przecinek leśnych, które testują nerwy kierowców. Jest to etap cieszący się dużą popularnością wśród kibiców.",
                            ImgName = "VRW_003.PNG",
                            Name = "Myherin"
                        },
                        new
                        {
                            StageCode = 44,
                            Description = "Pierwszy asfaltowy etap rajdowych mistrzostw Wielkiej Brytanii jest jak dynamit. Krótki, ostry i wąski. Premio wane tutaj będzie panowanie nad samochodem i konfigu racja zawieszenia, gdyż na drodze często porozrzu cane są pozostałości prac rolniczych. Uważaj, aby nie uderzyć w dom znajdujący się w pobliżu mety.",
                            ImgName = "VRW_004.PNG",
                            Name = "Hafren"
                        },
                        new
                        {
                            StageCode = 45,
                            Description = "Jeden z klasycznych etapów w Północnej Irlandii, Hamil ton's Folly to prawie 16 km wyboistej, wąskiej drogi w górach Mourne. Ze swoimi wielkimi wyskoczniami jest trudnym początkiem zarówno dla kierowcy, jak i pilota, zwłaszcza w mokrych warunkach. Wiele załóg wypadało już na pierwszej przeszkodzie.",
                            ImgName = "VRW_005.PNG",
                            Name = "Dyfi"
                        },
                        new
                        {
                            StageCode = 46,
                            Description = "Pierwszy etap ostatniej rundy rajdu Mobil 1 jest dobrym wprowadzeniem do Manx i jednocześnie surową próbą. Rozpoczyna się na malowniczym moście i biegnie kilka kilometrów wzdłuż morza, po czym wcina się w głąb lądu do szybszych dróg w pobliżu mety.",
                            ImgName = "VRW_006.PNG",
                            Name = "Gartheiniog"
                        },
                        new
                        {
                            StageCode = 51,
                            Description = "Odcinek ten wykorzystuje w paru miejscach bardzo bliskie rozjazdy, tak że kierowcy będą odwiedzać te same miej sca kilkukrotnie. Mimo to Dyfi jest bardzo lubiany. Zaśnieżone drogi są niezwykle śliskie i wymagają dosko nałego panowania nad pojazdem, zwłaszcza gdy samo chody wspinają się serpentynami na dwa wzniesienia.",
                            ImgName = "UL_001.PNG",
                            Name = "Hamilton's Folly"
                        },
                        new
                        {
                            StageCode = 52,
                            Description = "Jeżeli tylko w Kieldar jest jakiś łatwy etap, to Riccarton zasługuje na to miano. Jest krótki, posiada kręty start i szybkie, szerokie zakończenie. Ze względu na znacznie szersze drogi i płytkie rowy zmniejsza się również praw dopodobieństwo nieszczęśliwego wypadku.",
                            ImgName = "UL_002.PNG",
                            Name = "Tyrones Ditches"
                        },
                        new
                        {
                            StageCode = 53,
                            Description = "Po czterech krótkich sprawdzianach, Glentrool sprowa dza kierowców na ziemię swoimi 29 najtrudniejszymi, leśnymi kilometrami w Szkocji. Jego drogi są stosunkowo szybkie, ale można jeszcze przyspieszyć jazdę ścinając wybrane zakręty. Etap przyspiesza zbliżając się do koń ca lotnym finiszem premiującym umiejętności i odwagę.",
                            ImgName = "UL_003.PNG",
                            Name = "Feeney"
                        },
                        new
                        {
                            StageCode = 54,
                            Description = "Mając niewiele ponad 3 km, Lengton jest najkrótszym etapem w serii Mobil 1, ale kierowcy i tak nie mogą na nim odpocząć. Na swoim krótkim dystansie ma odrobinę wszystkiego, w tym również serię wiraży i kilka sko czni. Odcinek jest lubiany przez kibiców, więc w ciem ności mogą przeszkadzać błyski fotograficznych fleszy.",
                            ImgName = "UL_004.PNG",
                            Name = "Parkanaur"
                        },
                        new
                        {
                            StageCode = 55,
                            Description = "Etap ten daje kierowcy fałszywe poczucie bezpie czeństwa z kilkoma szybkimi prostymi na początkowych kilometrach, ale wkrótce staje się znacznie trudniejszy, gdy załogi trafiają na długie, kręte drogi wiodące w górę i w dół gór Coolnasillagh. Wracając na niziny, samochody trafiają na wąskie drogi poprzeplatane szybkimi prostymi.",
                            ImgName = "UL_005.PNG",
                            Name = "Lisnamuck"
                        },
                        new
                        {
                            StageCode = 56,
                            Description = "W ciągu dnia Injebreck jest jednym z najbardziej wymaga jących etapów Manx. W ciemności potrafi załamać sezon. Posiada bardzo szybkie, górskie drogi poprzecinane os trymi serpentynami. Uważaj na ostry wiraż w prawo tuż po starcie, gdyż inaczej będziesz musiał złapać najbliższy prom do domu.",
                            ImgName = "UL_006.PNG",
                            Name = "Tardree"
                        },
                        new
                        {
                            StageCode = 61,
                            Description = "Jest to górzysty odcinek, który dwukrotnie prowadzi  wokół zboczy góry na dwóch różnych wysokościach. Drogi są niezwykle szybkie, ale największe prędkości często ograniczane są drzewami rosnącymi blisko trasy. Nawierzchnia pokryta jest ostrymi krzemieniami, co sprawia, że walka często kończy się złapaniem gumy.",
                            ImgName = "PIR_001.PNG",
                            Name = "Chirdonhead"
                        },
                        new
                        {
                            StageCode = 62,
                            Description = "Drugi etap pozwala znacznie rozpędzić się już od linii star towej, posiadając jeden z najszybszych odcinków dróg w Kielder. Falstone wspina się do najwyższego punktu w całym kompleksie i jest lubianym odcinkiem, ale jego nawierzchnia może być bardziej ostra niż zazwyczaj, powodując przebicia opon.",
                            ImgName = "PIR_002.PNG",
                            Name = "Falstone"
                        },
                        new
                        {
                            StageCode = 63,
                            Description = "Etap ten wymaga od załóg jazdy wokół południowego i zachodniego stoku wzniesienia. Jest jednym z najszyb szych w rajdzie, mimo że średnie prędkości mogą być obniżane z powodu słabej porannej widoczności. Będziesz miał szczęście, jeżeli zobaczysz choćby jednego kibica, gdyż nie można się tu dostać z głównej drogi.",
                            ImgName = "PIR_003.PNG",
                            Name = "Kershope"
                        },
                        new
                        {
                            StageCode = 64,
                            Description = "Bothwell jest kolejnym szkockim sprawdzianem wymaga jącym wysokiego poziomu koncentracji. Posiada bardziej kręte fragmenty i ciasne wiraże w pobliżu Crichness, ale kierowcy będą raczej pamiętać fenomenalne prędkości osiągane na najszybszych prostych w pobliżu mety.",
                            ImgName = "PIR_004.PNG",
                            Name = "Pundershaw"
                        },
                        new
                        {
                            StageCode = 65,
                            Description = "Ten południowy, etap zlokalizowany w pobliżu granicznego miasta Newry, jest wielką próbą dla kierowców. Ma szyb ki start, ale wkrótce trasa zwęża się na krętych dro gach, które mogą być zdradliwe dzięki nieprzewidywalnej irlandzkiej pogodzie. Ostatnie kilometry są bardzo szyb kie i prowadzą po szerokim, gładkim asfalcie.",
                            ImgName = "PIR_005.PNG",
                            Name = "Riccarton"
                        },
                        new
                        {
                            StageCode = 66,
                            Description = "Większość tego etapu rozpoczynającego się tuż za mias tem Peel, wiedzie przez szybkie, wąskie drogi, ale prawie 5 km sprawdzianu prowadzi przez szerszą, główną drogę. W Ostatnich latach na etapie Ballagyr wybili się jedni z największych mistrzów Mobil 1 BRC, wśród nich m.in. Gwyndaf Evans i Alister McRae w 1997 roku.",
                            ImgName = "PIR_006.PNG",
                            Name = "Newcastleton"
                        },
                        new
                        {
                            StageCode = 71,
                            Description = "Kompleks Hafren daje odcinkowi wiele możliwości i jest jednym z najpopularniejszych miejsc w Walii nawet podczas opadów śniegu. Otwierający odcinek jest niezwykle szybki, ale wkrótce następuje po nim znacznie bardziej kręty i techniczny fragment utrudniony przez mroźną pogodę.",
                            ImgName = "JC_001.PNG",
                            Name = "Moon and Star"
                        },
                        new
                        {
                            StageCode = 72,
                            Description = "Czwartym sprawdzianem Rajdu Pirelli jest najdłuższy etap rajdowych mistrzostw Wielkiej Brytanii. Punder shaw wykorzystuje fragmenty odcinka Chirdonhead i, jako taki, posiada mnóstwo długich i szybkich sekcji. Wymaga wysokiego poziomu koncentracji, gdy widocz ność jest ograniczona przez zamarzającą mżawkę.",
                            ImgName = "JC_002.PNG",
                            Name = "Bothwell"
                        },
                        new
                        {
                            StageCode = 73,
                            Description = "Czwarty sprawdzian, Black Loch, ma coś dla każdego. Posiada dobrą, twardą nawierzchnię i samochody for muły 2 będą się rozkoszować szybkimi zjazdami, które stanowią większą część kilku początkowych kilometrów. Wielkie przepaście z prawej strony mogą sprawić, iż wielu kierowców zdejmie jednak nogę z gazu.",
                            ImgName = "JC_003.PNG",
                            Name = "Whitchester"
                        },
                        new
                        {
                            StageCode = 74,
                            Description = "Eccles zwiastuje rozpoczęcie etapów Merse i opiera się na stosunkowo płaskim terenie na północ od rzeki Tweed. Składa się z wąskich wiejskich dróg, długich, szybkich prostych i kilku niezwykle ciasnych łuków. Wysokie żywopłoty, wymuszają precyzyjne prowadzenie samo chodu. Światło o zmierzchu również nikomu nie sprzyja.",
                            ImgName = "JC_004.PNG",
                            Name = "Eccles"
                        },
                        new
                        {
                            StageCode = 75,
                            Description = "Etap ten demonstruje jak bardzo skomplikowane potrafią być irlandzkie drogi. Jest wąski, wyboisty i kręty oraz posiada wiele zmian kierunku jazdy, co wymaga od kie rowcy koncentracji i doskonałego prowadzenia samo chodu. W lesie Parkanaur jest wiele niebezpiecznych serii wybojów.",
                            ImgName = "JC_005.PNG",
                            Name = "Langton"
                        },
                        new
                        {
                            StageCode = 76,
                            Description = "Kolejna legenda Manx, Tholt-y-Will, rozpoczyna się na sławnym moście i przechodzi w połowie drogi w pobliżu pubu licznie odwiedzanego przez kibiców. Dwie serpen tyny prowadzą zawodników do szybkiej części znajdującej się na szczycie góry. W górnych odcinkach często wys tępuje mgła oraz znajduje się tam wiele pastwisk.",
                            ImgName = "JC_006.PNG",
                            Name = "Fogo"
                        });
                });

            modelBuilder.Entity("RC2K.DomainModel.StageDetails", b =>
                {
                    b.Property<int>("StageCode")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Asphalt")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Dirt")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Gravel")
                        .HasColumnType("INTEGER");

                    b.Property<float>("Length")
                        .HasColumnType("REAL");

                    b.Property<int>("Mood")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Snow")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Temp")
                        .HasColumnType("INTEGER");

                    b.Property<float>("Wind")
                        .HasColumnType("REAL");

                    b.HasKey("StageCode");

                    b.ToTable("StageDetails");

                    b.HasData(
                        new
                        {
                            StageCode = 21,
                            Asphalt = 100,
                            Dirt = 0,
                            Gravel = 0,
                            Length = 10.17f,
                            Mood = 2,
                            Snow = 0,
                            Temp = 31,
                            Wind = 2.4f
                        },
                        new
                        {
                            StageCode = 22,
                            Asphalt = 99,
                            Dirt = 1,
                            Gravel = 0,
                            Length = 14.02f,
                            Mood = 2,
                            Snow = 0,
                            Temp = 29,
                            Wind = 6.4f
                        },
                        new
                        {
                            StageCode = 23,
                            Asphalt = 77,
                            Dirt = 0,
                            Gravel = 23,
                            Length = 17.85f,
                            Mood = 4,
                            Snow = 0,
                            Temp = 26,
                            Wind = 0.3f
                        },
                        new
                        {
                            StageCode = 24,
                            Asphalt = 98,
                            Dirt = 0,
                            Gravel = 2,
                            Length = 6.6f,
                            Mood = 4,
                            Snow = 0,
                            Temp = 24,
                            Wind = 0f
                        },
                        new
                        {
                            StageCode = 25,
                            Asphalt = 99,
                            Dirt = 0,
                            Gravel = 1,
                            Length = 18.25f,
                            Mood = 8,
                            Snow = 0,
                            Temp = 22,
                            Wind = 0f
                        },
                        new
                        {
                            StageCode = 26,
                            Asphalt = 98,
                            Dirt = 1,
                            Gravel = 1,
                            Length = 22.3f,
                            Mood = 8,
                            Snow = 0,
                            Temp = 21,
                            Wind = 0.2f
                        },
                        new
                        {
                            StageCode = 31,
                            Asphalt = 7,
                            Dirt = 0,
                            Gravel = 93,
                            Length = 9.08f,
                            Mood = 8,
                            Snow = 0,
                            Temp = 7,
                            Wind = 0.3f
                        },
                        new
                        {
                            StageCode = 32,
                            Asphalt = 0,
                            Dirt = 0,
                            Gravel = 100,
                            Length = 8.87f,
                            Mood = 1,
                            Snow = 0,
                            Temp = 12,
                            Wind = 0f
                        },
                        new
                        {
                            StageCode = 33,
                            Asphalt = 0,
                            Dirt = 0,
                            Gravel = 100,
                            Length = 10.27f,
                            Mood = 2,
                            Snow = 0,
                            Temp = 16,
                            Wind = 0.2f
                        },
                        new
                        {
                            StageCode = 34,
                            Asphalt = 0,
                            Dirt = 0,
                            Gravel = 100,
                            Length = 9.82f,
                            Mood = 258,
                            Snow = 0,
                            Temp = 12,
                            Wind = 0.8f
                        },
                        new
                        {
                            StageCode = 35,
                            Asphalt = 0,
                            Dirt = 0,
                            Gravel = 100,
                            Length = 29.71f,
                            Mood = 258,
                            Snow = 0,
                            Temp = 6,
                            Wind = 6.1f
                        },
                        new
                        {
                            StageCode = 36,
                            Asphalt = 0,
                            Dirt = 0,
                            Gravel = 100,
                            Length = 30.42f,
                            Mood = 514,
                            Snow = 0,
                            Temp = 4,
                            Wind = 18.8f
                        },
                        new
                        {
                            StageCode = 41,
                            Asphalt = 0,
                            Dirt = 5,
                            Gravel = 95,
                            Length = 19.31f,
                            Mood = 2,
                            Snow = 0,
                            Temp = 13,
                            Wind = 1.9f
                        },
                        new
                        {
                            StageCode = 42,
                            Asphalt = 0,
                            Dirt = 0,
                            Gravel = 100,
                            Length = 15.3f,
                            Mood = 2,
                            Snow = 0,
                            Temp = 10,
                            Wind = 6f
                        },
                        new
                        {
                            StageCode = 43,
                            Asphalt = 0,
                            Dirt = 0,
                            Gravel = 100,
                            Length = 24.36f,
                            Mood = 258,
                            Snow = 0,
                            Temp = 7,
                            Wind = 6.1f
                        },
                        new
                        {
                            StageCode = 44,
                            Asphalt = 0,
                            Dirt = 0,
                            Gravel = 0,
                            Length = 24.33f,
                            Mood = 1026,
                            Snow = 100,
                            Temp = 2,
                            Wind = 6f
                        },
                        new
                        {
                            StageCode = 45,
                            Asphalt = 0,
                            Dirt = 0,
                            Gravel = 0,
                            Length = 26.34f,
                            Mood = 1028,
                            Snow = 100,
                            Temp = 0,
                            Wind = 12.9f
                        },
                        new
                        {
                            StageCode = 46,
                            Asphalt = 0,
                            Dirt = 0,
                            Gravel = 0,
                            Length = 20.39f,
                            Mood = 1032,
                            Snow = 100,
                            Temp = -2,
                            Wind = 21.4f
                        },
                        new
                        {
                            StageCode = 51,
                            Asphalt = 97,
                            Dirt = 3,
                            Gravel = 0,
                            Length = 15.69f,
                            Mood = 513,
                            Snow = 0,
                            Temp = 14,
                            Wind = 46.2f
                        },
                        new
                        {
                            StageCode = 52,
                            Asphalt = 97,
                            Dirt = 3,
                            Gravel = 0,
                            Length = 18.76f,
                            Mood = 1,
                            Snow = 0,
                            Temp = 16,
                            Wind = 25.6f
                        },
                        new
                        {
                            StageCode = 53,
                            Asphalt = 96,
                            Dirt = 1,
                            Gravel = 3,
                            Length = 17.86f,
                            Mood = 2,
                            Snow = 0,
                            Temp = 19,
                            Wind = 17.7f
                        },
                        new
                        {
                            StageCode = 54,
                            Asphalt = 74,
                            Dirt = 1,
                            Gravel = 25,
                            Length = 18.09f,
                            Mood = 2,
                            Snow = 0,
                            Temp = 24,
                            Wind = 16.7f
                        },
                        new
                        {
                            StageCode = 55,
                            Asphalt = 74,
                            Dirt = 1,
                            Gravel = 25,
                            Length = 14.66f,
                            Mood = 2,
                            Snow = 0,
                            Temp = 26,
                            Wind = 6.6f
                        },
                        new
                        {
                            StageCode = 56,
                            Asphalt = 88,
                            Dirt = 5,
                            Gravel = 7,
                            Length = 15f,
                            Mood = 2,
                            Snow = 0,
                            Temp = 23,
                            Wind = 3.7f
                        },
                        new
                        {
                            StageCode = 61,
                            Asphalt = 0,
                            Dirt = 0,
                            Gravel = 100,
                            Length = 38.78f,
                            Mood = 8,
                            Snow = 0,
                            Temp = 3,
                            Wind = 6.4f
                        },
                        new
                        {
                            StageCode = 62,
                            Asphalt = 0,
                            Dirt = 0,
                            Gravel = 100,
                            Length = 29.43f,
                            Mood = 2,
                            Snow = 0,
                            Temp = 12,
                            Wind = 4.7f
                        },
                        new
                        {
                            StageCode = 63,
                            Asphalt = 0,
                            Dirt = 0,
                            Gravel = 100,
                            Length = 29.76f,
                            Mood = 2,
                            Snow = 0,
                            Temp = 10,
                            Wind = 5.1f
                        },
                        new
                        {
                            StageCode = 64,
                            Asphalt = 0,
                            Dirt = 0,
                            Gravel = 100,
                            Length = 42.82f,
                            Mood = 2050,
                            Snow = 0,
                            Temp = 5,
                            Wind = 19.5f
                        },
                        new
                        {
                            StageCode = 65,
                            Asphalt = 0,
                            Dirt = 0,
                            Gravel = 100,
                            Length = 14.16f,
                            Mood = 2050,
                            Snow = 0,
                            Temp = 4,
                            Wind = 20f
                        },
                        new
                        {
                            StageCode = 66,
                            Asphalt = 0,
                            Dirt = 0,
                            Gravel = 100,
                            Length = 29.32f,
                            Mood = 514,
                            Snow = 0,
                            Temp = 3,
                            Wind = 16.1f
                        },
                        new
                        {
                            StageCode = 71,
                            Asphalt = 95,
                            Dirt = 1,
                            Gravel = 4,
                            Length = 7.26f,
                            Mood = 4,
                            Snow = 0,
                            Temp = 22,
                            Wind = 1.3f
                        },
                        new
                        {
                            StageCode = 72,
                            Asphalt = 90,
                            Dirt = 1,
                            Gravel = 9,
                            Length = 10.51f,
                            Mood = 4,
                            Snow = 0,
                            Temp = 21,
                            Wind = 1.1f
                        },
                        new
                        {
                            StageCode = 73,
                            Asphalt = 91,
                            Dirt = 0,
                            Gravel = 9,
                            Length = 11.72f,
                            Mood = 4,
                            Snow = 0,
                            Temp = 19,
                            Wind = 1.1f
                        },
                        new
                        {
                            StageCode = 74,
                            Asphalt = 85,
                            Dirt = 2,
                            Gravel = 13,
                            Length = 9.99f,
                            Mood = 8,
                            Snow = 0,
                            Temp = 14,
                            Wind = 1.6f
                        },
                        new
                        {
                            StageCode = 75,
                            Asphalt = 80,
                            Dirt = 6,
                            Gravel = 14,
                            Length = 3.25f,
                            Mood = 8,
                            Snow = 0,
                            Temp = 12,
                            Wind = 1.9f
                        },
                        new
                        {
                            StageCode = 76,
                            Asphalt = 83,
                            Dirt = 0,
                            Gravel = 17,
                            Length = 11.65f,
                            Mood = 8,
                            Snow = 0,
                            Temp = 10,
                            Wind = 1.8f
                        });
                });

            modelBuilder.Entity("RC2K.DomainModel.StageWaypoints", b =>
                {
                    b.Property<int>("StageCode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ApiHint")
                        .HasColumnType("TEXT");

                    b.Property<string>("Path")
                        .HasColumnType("TEXT");

                    b.Property<string>("Waypoints")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("StageCode");

                    b.ToTable("StageWaypoints");

                    b.HasData(
                        new
                        {
                            StageCode = 21,
                            ApiHint = "bike",
                            Waypoints = "54.1412097,-4.4701409;54.1355627,-4.4864447;54.1277141,-4.5221752;54.1266989,-4.5372641;54.114791,-4.569775;54.120478,-4.57988"
                        },
                        new
                        {
                            StageCode = 22,
                            ApiHint = "car",
                            Waypoints = "54.2262301,-4.6734796;54.2282370,-4.6504770;54.2179001,-4.6418939;54.2319497,-4.6293626;54.242985,-4.618033;54.248401,-4.6355424;54.2596334,-4.6223245;54.2722654,-4.6018968;54.2678098,-4.5894544;54.2610085,-4.5824171"
                        },
                        new
                        {
                            StageCode = 23,
                            ApiHint = "bike",
                            Waypoints = "54.2925137,-4.5794562;54.3049822,-4.575546;54.3030134,-4.5671377;54.3301914,-4.5553174;54.3299322,-4.5537086;54.3207096,-4.5492764;54.3219861,-4.5427103;54.3196834,-4.5364447;54.3234629,-4.5338698;54.327267,-4.5310803;54.3269167,-4.5462294;54.3299948,-4.5507784;54.3388275,-4.55198;54.3379268,-4.53932;54.3355769,-4.5327248;54.3312438,-4.5021903;54.3324972,-4.48343;54.323525,-4.478758"
                        },
                        new
                        {
                            StageCode = 24,
                            ApiHint = "car",
                            Waypoints = "54.3156717,-4.4849128;54.3151715,-4.4887726;54.3073269,-4.4898721;54.2995679,-4.4853024;54.2764154,-4.4935351;54.2708857,-4.4947851;54.2664541,-4.483406"
                        },
                        new
                        {
                            StageCode = 25,
                            ApiHint = "car",
                            Waypoints = "54.2392179,-4.6001656;54.2438606,-4.577607;54.2523886,-4.5775069;54.2471995,-4.5652364;54.2474655,-4.5387513;54.2314794,-4.5224346;54.2007131,-4.5256629;54.2028513,-4.5226207;54.2053066,-4.5174728;54.2051566,-4.5116617;54.1944018,-4.5136428;54.1828935,-4.5065698;54.1872281,-4.4941888;54.1839937,-4.4765511"
                        },
                        new
                        {
                            StageCode = 26,
                            ApiHint = "car",
                            Waypoints = "54.1015818,-4.6833901;54.1102406,-4.6949709;54.1166429,-4.6885336;54.1135748,-4.682729;54.1019256,-4.6802267;54.1092891,-4.6676369;54.1173622,-4.6557725;54.127605,-4.661999;54.1351724,-4.6677933;54.1312624,-4.6824002;54.119058,-4.6872147;54.1216356,-4.6869764;54.1276671,-4.689926;54.136638,-4.687929;54.1481165,-4.6859442;54.1637829,-4.6670789;54.1698884,-4.6659241;54.178584,-4.6544162;54.1996249,-4.6429132"
                        },
                        new
                        {
                            StageCode = 31,
                            ApiHint = "car",
                            Waypoints = "55.2491075,-3.2533364;55.2623553,-3.2553117;55.2742391,-3.261627;55.2706414,-3.2592452;55.2656658,-3.2535073;55.2665569,-3.2493774;55.2547615,-3.2474987;55.2457889,-3.2454704;55.2333417,-3.2460206;55.2404609,-3.2386813;55.2555436,-3.2362395;55.264432,-3.2413363;55.2691266,-3.2324528;55.2653856,-3.2295561"
                        },
                        new
                        {
                            StageCode = 32,
                            ApiHint = "car",
                            Waypoints = "55.5799576,-2.8470598;55.5815481,-2.868296;55.5744477,-2.8748228;55.573461,-2.8886166;55.5774031,-2.8951713;55.5824665,-2.8943305;55.5893707,-2.9080469;55.5950664,-2.9080214;55.6025383,-2.8901209"
                        },
                        new
                        {
                            StageCode = 33,
                            ApiHint = "car",
                            Waypoints = "55.6215321,-3.0942564;55.6133437,-3.0946008;55.6203456,-3.0974053;55.6227274,-3.1062642;55.6345814,-3.1147908;55.6339778,-3.1219431;55.6227377,-3.1145974;55.6156676,-3.117815;55.6109905,-3.1191319;55.6185788,-3.1215048;55.6277337,-3.1219804;55.6340654,-3.1254894"
                        },
                        new
                        {
                            StageCode = 34,
                            ApiHint = "car",
                            Waypoints = "54.9915741,-4.4096625;54.9940791,-4.4085619;55.0039196,-4.396167;55.018781,-4.3734123;55.0236645,-4.3636705;55.0293507,-4.3527738;55.0311463,-4.3657343;55.0360652,-4.3698971;55.0406515,-4.3618206;55.0538223,-4.3668409;55.0658635,-4.3472072"
                        },
                        new
                        {
                            StageCode = 35,
                            ApiHint = "car",
                            Waypoints = "55.1114868,-4.6426859;55.1304444,-4.6233196;55.1411236,-4.6149022;55.1507622,-4.6161897;55.1588269,-4.6301213;55.1726035,-4.6275893;55.1720857,-4.6019906;55.160703,-4.5960898;55.1503151,-4.5955149;55.1481937,-4.5926993;55.1484859,-4.5833043;55.1444888,-4.5823218;55.1320066,-4.5708257;55.1288823,-4.5784403;55.1252913,-4.5971009;55.1224381,-4.6028961;55.1061865,-4.6194355;55.0943557,-4.6173425;55.1047824,-4.5859976;55.1037088,-4.574991;55.0901618,-4.5724581;55.0792513,-4.5743539"
                        },
                        new
                        {
                            StageCode = 36,
                            ApiHint = "bike",
                            Waypoints = "55.2268885,-3.6352024;55.2217208,-3.6315674;55.2185621,-3.6221003;55.2179508,-3.6177368;55.2211677,-3.617941;55.2250101,-3.6192424;55.226058,-3.6189106;55.2329704,-3.6206734;55.2330286,-3.6178571;55.228794,-3.608627;55.2267129,-3.6031663;55.2224776,-3.6076829;55.2193165,-3.6105666;55.2179336,-3.6133225;55.2150076,-3.6138584;55.2071168,-3.6096184;55.2039945,-3.6096827;55.2021332,-3.607537;55.2055128,-3.6044256;55.2089656,-3.6005203;55.2142789,-3.6008422;55.2187714,-3.6091892;55.218906,-3.6057774;55.2192879,-3.6007538;55.2229254,-3.6006424;55.2250257,-3.5970871;55.2249401,-3.5957138;55.2306795,-3.5860578;55.234693,-3.5806076;55.2442111,-3.5709302;55.2465474,-3.5719172;55.2435872,-3.579642;55.2467187,-3.582174;55.2544729,-3.5782902;55.2591198,-3.5693852;55.2572855,-3.5655014;55.2546441,-3.5630552;55.251028,-3.5589941;55.2491081,-3.5530995;55.2481044,-3.5469243;55.2436823,-3.5418463;55.2407873,-3.542918;55.2342109,-3.5405193;55.2317081,-3.5411573;55.2297872,-3.5430711;55.2271652,-3.5453581;55.2280264,-3.5503181;55.2284517,-3.5527062;55.2302307,-3.5524663;55.2325444,-3.5568553;55.2309437,-3.5586415;55.2276403,-3.5611423;55.2216148,-3.5699458;55.2207706,-3.5765039;55.2159472,-3.5755178;55.2109085,-3.5727906;55.2082894,-3.5822397;55.2056248,-3.5833369;55.2030474,-3.5949474;55.1993282,-3.5957611;55.1957118,-3.5934518;55.1899437,-3.5886035;55.188385,-3.5835765"
                        },
                        new
                        {
                            StageCode = 41,
                            ApiHint = "",
                            Waypoints = ""
                        },
                        new
                        {
                            StageCode = 42,
                            ApiHint = "",
                            Waypoints = ""
                        },
                        new
                        {
                            StageCode = 43,
                            ApiHint = "",
                            Waypoints = ""
                        },
                        new
                        {
                            StageCode = 44,
                            ApiHint = "",
                            Waypoints = ""
                        },
                        new
                        {
                            StageCode = 45,
                            ApiHint = "",
                            Waypoints = ""
                        },
                        new
                        {
                            StageCode = 46,
                            ApiHint = "",
                            Waypoints = ""
                        },
                        new
                        {
                            StageCode = 51,
                            ApiHint = "car",
                            Waypoints = "54.2695441,-5.9436646;54.2744611,-5.9516598;54.277376,-5.9690744;54.2800867,-5.9654936;54.2832844,-5.9588631;54.2871588,-5.9624096;54.2872168,-5.9476434;54.2976729,-5.9428498;54.3132324,-5.9487013;54.3241757,-5.9448057;54.3345806,-5.9465961;54.3407904,-5.942469;54.3451774,-5.935004;54.3558599,-5.9179497;54.3598739,-5.9075108"
                        },
                        new
                        {
                            StageCode = 52,
                            ApiHint = "car",
                            Waypoints = "54.2102263,-6.3606529;54.2190401,-6.3633142;54.2264219,-6.3702173;54.2309064,-6.3685287;54.2361336,-6.3708844;54.2383631,-6.3812244;54.2383251,-6.3879784;54.2344646,-6.3901814;54.2319624,-6.3995735;54.2363806,-6.4000477;54.2394021,-6.3933767;54.2423015,-6.3800764;54.2489889,-6.383954;54.2563833,-6.391347;54.2566999,-6.3966213;54.2502027,-6.4059393;54.2521635,-6.4138816;54.2511755,-6.428105;54.255166,-6.4236172;54.2579435,-6.4161632;54.2600201,-6.4132316;54.264264,-6.4139728;54.2690647,-6.412953;54.2755007,-6.4089856;54.2828846,-6.4018213;54.289814,-6.3919248"
                        },
                        new
                        {
                            StageCode = 53,
                            ApiHint = "car",
                            Waypoints = "54.4257316,-6.1650349;54.4271903,-6.1568478;54.428679,-6.1523937;54.4329029,-6.1545985;54.4352928,-6.157466;54.4415002,-6.1417045;54.445447,-6.1474803;54.4470748,-6.155164;54.4402303,-6.1616851;54.4344398,-6.1718923;54.4387374,-6.1816485;54.4343812,-6.189752;54.4331457,-6.2018448;54.4364948,-6.2079331;54.4438446,-6.2100906;54.445235,-6.2193526;54.4509796,-6.2238791;54.4568921,-6.2225654;54.4610105,-6.2406527;54.4665823,-6.2367736;54.4695446,-6.2123403;54.4703659,-6.2058873"
                        },
                        new
                        {
                            StageCode = 54,
                            ApiHint = "car",
                            Waypoints = "54.489931,-6.9113891;54.4909936,-6.9116337;54.4966288,-6.909339;54.5036831,-6.8999815;54.5067101,-6.9087565;54.5031285,-6.9123935;54.4957244,-6.9311578;54.4957487,-6.937411;54.5023434,-6.9350269;54.5093916,-6.9236487;54.5106318,-6.9232709;54.5100352,-6.9163916;54.5072182,-6.9100547;54.5202185,-6.8944553;54.5197694,-6.8876165;54.5127161,-6.8839147;54.5099965,-6.890879;54.5038619,-6.8974968;54.5000972,-6.8931676;54.5039104,-6.8803474;54.4975953,-6.872693;54.503813,-6.8600696;54.4992589,-6.8520387"
                        },
                        new
                        {
                            StageCode = 55,
                            ApiHint = "car",
                            Waypoints = "54.8128416,-6.7295615;54.81754,-6.7337886;54.8172436,-6.7487521;54.8153065,-6.7639324;54.8149188,-6.7795234;54.8202896,-6.7845561;54.8246029,-6.7718382;54.8282303,-6.769607;54.8414981,-6.7790779;54.8427258,-6.758997;54.8318105,-6.7513209;54.8236991,-6.7543702;54.8284121,-6.7422515"
                        },
                        new
                        {
                            StageCode = 56,
                            ApiHint = "car",
                            Waypoints = "54.7237015,-6.1354;54.7321632,-6.147047;54.7418747,-6.1520021;54.7493214,-6.1476175;54.7516124,-6.1549793;54.7571991,-6.1698003;54.7647991,-6.1714603;54.7622382,-6.1832609;54.7536172,-6.1860396;54.7434054,-6.1775533;54.7489253,-6.1575969;54.7477172,-6.1553956;54.7403015,-6.1553956;54.7364681,-6.16135;54.7260286,-6.1578856"
                        },
                        new
                        {
                            StageCode = 61,
                            ApiHint = "",
                            Waypoints = ""
                        },
                        new
                        {
                            StageCode = 62,
                            ApiHint = "",
                            Waypoints = ""
                        },
                        new
                        {
                            StageCode = 63,
                            ApiHint = "",
                            Waypoints = ""
                        },
                        new
                        {
                            StageCode = 64,
                            ApiHint = "",
                            Waypoints = ""
                        },
                        new
                        {
                            StageCode = 65,
                            ApiHint = "",
                            Waypoints = ""
                        },
                        new
                        {
                            StageCode = 66,
                            ApiHint = "",
                            Waypoints = ""
                        },
                        new
                        {
                            StageCode = 71,
                            ApiHint = "car",
                            Waypoints = "55.86020390016135,-2.404705916624326;55.86052336001392,-2.41880253919625;55.86602723773092,-2.426904690554126;55.87192908057129,-2.4371389870061795;55.878946320901825,-2.4348646989057228;55.885324529839565,-2.4232089723908845;55.89106402187944,-2.4168125371083504;55.8964838738952,-2.4023139504679416;55.903576359936224,-2.392221797022166"
                        },
                        new
                        {
                            StageCode = 72,
                            ApiHint = "car",
                            Waypoints = "55.8613738,-2.5075883;55.8694904,-2.5104257;55.8797404,-2.5072733;55.8865856,-2.5069823;55.8927304,-2.5062688;55.8919817,-2.4966696;55.8761643,-2.4868177;55.8681212,-2.498876;55.8611062,-2.4927751;55.8579104,-2.4942655"
                        },
                        new
                        {
                            StageCode = 73,
                            ApiHint = "car",
                            Waypoints = "55.8076268,-2.4766033;55.8201039,-2.4563524;55.8311692,-2.4333892;55.8174765,-2.3960529;55.8368886,-2.3934378;55.8449128,-2.3752417;55.8480299,-2.3807008"
                        },
                        new
                        {
                            StageCode = 74,
                            ApiHint = "bike",
                            Waypoints = "55.6978028,-2.4279197;55.6866311,-2.4188734;55.6801149,-2.4378057;55.6715428,-2.4267619;55.6707486,-2.4111336;55.675335,-2.4105145;55.6779441,-2.4115849;55.6794172,-2.4000355;55.668714,-2.3777032"
                        },
                        new
                        {
                            StageCode = 75,
                            ApiHint = "car",
                            Waypoints = "55.7586322,-2.3469772;55.7629178,-2.3557926;55.7685173,-2.3544878;55.7652199,-2.3467925;55.7600104,-2.3427473"
                        },
                        new
                        {
                            StageCode = 76,
                            ApiHint = "car",
                            Waypoints = "55.7376067,-2.3320954;55.7369066,-2.3462381;55.7348744,-2.3636395;55.7350628,-2.3698927;55.737194,-2.3674458;55.7286223,-2.3873504;55.7303888,-2.3923697;55.7329559,-2.3921815;55.7339215,-2.3938964;55.7394555,-2.3898601;55.7455184,-2.371184;55.745436,-2.3652236;55.7397616,-2.3643452;55.7442588,-2.3452927;55.7451523,-2.3362839"
                        });
                });

            modelBuilder.Entity("RC2K.DomainModel.TimeEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CarId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DriverId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StageId")
                        .HasColumnType("INTEGER");

                    b.Property<TimeOnly>("Time")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UploadTime")
                        .HasColumnType("TEXT");

                    b.Property<int?>("VerifyInfoId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CarId");

                    b.HasIndex("DriverId");

                    b.HasIndex("StageId");

                    b.HasIndex("VerifyInfoId");

                    b.ToTable("TimeEntries");
                });

            modelBuilder.Entity("RC2K.DomainModel.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DriverId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Roles")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("RC2K.DomainModel.VerifyInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Comment")
                        .HasColumnType("TEXT");

                    b.Property<int>("VerifierId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("VerifyDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("VerifierId");

                    b.ToTable("VerifyInfos");
                });

            modelBuilder.Entity("RC2K.DomainModel.Driver", b =>
                {
                    b.HasOne("RC2K.DomainModel.User", "User")
                        .WithOne("Driver")
                        .HasForeignKey("RC2K.DomainModel.Driver", "UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RC2K.DomainModel.Stage", b =>
                {
                    b.HasOne("RC2K.DomainModel.StageData", "StageData")
                        .WithMany()
                        .HasForeignKey("Code")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RC2K.DomainModel.StageWaypoints", "StageWaypoints")
                        .WithMany()
                        .HasForeignKey("Code")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StageData");

                    b.Navigation("StageWaypoints");
                });

            modelBuilder.Entity("RC2K.DomainModel.StageDetails", b =>
                {
                    b.HasOne("RC2K.DomainModel.StageData", null)
                        .WithOne("StageDetails")
                        .HasForeignKey("RC2K.DomainModel.StageDetails", "StageCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RC2K.DomainModel.TimeEntry", b =>
                {
                    b.HasOne("RC2K.DomainModel.Car", "Car")
                        .WithMany()
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RC2K.DomainModel.Driver", "Driver")
                        .WithMany()
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RC2K.DomainModel.Stage", "Stage")
                        .WithMany()
                        .HasForeignKey("StageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RC2K.DomainModel.VerifyInfo", "VerifyInfo")
                        .WithMany()
                        .HasForeignKey("VerifyInfoId");

                    b.Navigation("Car");

                    b.Navigation("Driver");

                    b.Navigation("Stage");

                    b.Navigation("VerifyInfo");
                });

            modelBuilder.Entity("RC2K.DomainModel.VerifyInfo", b =>
                {
                    b.HasOne("RC2K.DomainModel.User", "Verifier")
                        .WithMany()
                        .HasForeignKey("VerifierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Verifier");
                });

            modelBuilder.Entity("RC2K.DomainModel.StageData", b =>
                {
                    b.Navigation("StageDetails");
                });

            modelBuilder.Entity("RC2K.DomainModel.User", b =>
                {
                    b.Navigation("Driver");
                });
#pragma warning restore 612, 618
        }
    }
}
