name: SonarQube

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main # Triggers only on PRs targeting main

jobs:
  build:
    name: Build and analyze
    runs-on: windows-latest
    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'zulu'

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Shallow clones disabled for better relevancy of analysis

      - name: Cache SonarQube Cloud packages
        uses: actions/cache@v4
        with:
          path: ~\sonar\cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Cache SonarQube Cloud scanner
        id: cache-sonar-scanner
        uses: actions/cache@v4
        with:
          path: ${{ runner.temp }}\scanner
          key: ${{ runner.os }}-sonar-scanner
          restore-keys: ${{ runner.os }}-sonar-scanner

      - name: Install SonarQube Cloud scanner
        if: steps.cache-sonar-scanner.outputs.cache-hit != 'true'
        shell: powershell
        run: |
          New-Item -Path ${{ runner.temp }}\scanner -ItemType Directory
          dotnet tool update dotnet-sonarscanner --tool-path ${{ runner.temp }}\scanner

      - name: Build and analyze
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        shell: powershell
        run: |
          # Start building the base scanner command
          $sonarCmd = "${{ runner.temp }}\scanner\dotnet-sonarscanner begin /k:""TheKetrab_RC2K"" /o:""theketrab"" /d:sonar.token=""${{ secrets.SONAR_TOKEN }}"" /d:sonar.exclusions=""**/Migrations/*.cs"" /d:sonar.cs.opencover.reportsPaths=""**/coverage.opencover.xml"""

          # Dynamically append PR parameters ONLY if this run is an actual Pull Request
          if ("${{ github.event_name }}" -eq "pull_request") {
              $sonarCmd += " /d:sonar.pullrequest.key=""${{ github.event.pull_request.number }}"""
              $sonarCmd += " /d:sonar.pullrequest.branch=""${{ github.head_ref }}"""
              $sonarCmd += " /d:sonar.pullrequest.base=""${{ github.base_ref }}"""
          }

          # Invoke the dynamically built Sonar command
          Invoke-Expression $sonarCmd

          # Build the solution
          dotnet build "src/RC2K.sln"
          
          # Run tests and collect coverage
          dotnet test "src/RC2K.sln" --no-build -p:CollectCoverage=true -p:CoverletOutputFormat=opencover -p:CoverletOutput="TestResults/coverage.opencover.xml" /p:Exclude="[RC2K.DomainModel]*,[RC2K.Extensions]*,[RC2K.Parser]*,[RC2K.Presentation]*"
          
          # End Sonar analysis
          ${{ runner.temp }}\scanner\dotnet-sonarscanner end /d:sonar.token="${{ secrets.SONAR_TOKEN }}"